### PR TITLE
port to multiloader

### PR DESCRIPTION
**Pull request by Abbie5**
i also replaced a lot of the access widener usage with mixin accessors/invokers, i hope thats ok

### CODE REVIEW

**Comment by aratakileo** [comment]
Why were such code modifications made?
https://github.com/aratakileo/emogg/blob/8d6211a9a9084452eaee660ef524fc35c54b8b5f/xplat/src/main/java/pextystudios/emogg/gui/component/AbstractWidget.java#L86

**Comment by Abbie5** [comment]
those changes were made because i removed the access wideners for those fields, i can revert this if you like.

**Comment by aratakileo** [comment]
# Sorry, but not now
To be honest, I would like to delay porting at least until the first release version, because maintaining a multiloader project reduces the resources that could be directed to the implementation of this or that functionality or to improve the mod. Unifying the mod in this way makes the project cluttered, which can also negatively affect the development process.

Regarding the demand for porting. If you open the list of mods on modrinth.com and compare the number of downloads for the same version of Minecraft, it turns out that the number of downloads for Fabric / Quilt exceeds the number of downloads for Forge by an average of 6.2 times (if we take into account a sample of five mods on the first page). I also can't help but not the trend of a decrease in the number of mods that support Forge. This is especially noticeable if we take into account from the old versions to the newest.

**Comment by Abbie5** [comment]
That's understandable, thanks for clarifying.

**Pull request closed without merging**
