### PR TITLE
Fix some text beginning from the polar left side of the screen

### PR DESCRIPTION
**Pull request by unilock**
This PR fixes some text being printed at the polar left side of the screen instead of where it would normally appear - namely "example" / "placeholder" text: dark grey text that's printed in the background of some fields, and is immediately replaced by whatever the player types in.

It also updates the build environment and adds the dependencies of the mod to its `fabric.mod.json`.

### CODE REVIEW

**Comment by aratakileo** [comment]
About changes in `fabric.mod.json`: the dependency on the Minecraft version is added automatically using `util.gradle'. Added dependencies on `fabricloader` and `fabric-api` break compatibility with Quilt

**Comment by aratakileo** [comment]
Can you please present this problem with a screenshot?

**Comment by unilock** [comment]
> About changes in `fabric.mod.json`...

Oh, my mistake. I'll revert those changes then.  

> the dependency on the Minecraft version is added automatically using `util.gradle`

You can also do this with the `processResources` Gradle task, as Fabric does in their example mod: [link](https://github.com/FabricMC/fabric-example-mod/blob/e6c436b4344ec00406b02bc274ec19e33d6a56e0/build.gradle#L48-L54)

> added dependencies on `fabricloader` and `fabric-api` may break compatibility with Quilt

Quilt Loader / Quilted Fabric API will still provide the mod IDs for `fabricloader` and `fabric-api` to the dependency checker, though they may not always be up-to-date with the latest version of their upstream counterparts - in which case, it should be fine to just replace `"fabric-api": ">=0.83.0"` with `"fabric-api": "*"`.

> Can you please present this problem with a screenshot?

The issue can also be reproduced by moving the cursor to the beginning of any text field. Here's an example:

**Review by aratakileo — APPROVED** [review]
Since the mod does not interact with the `fabric-api` (especially since quilted fabric api was abandoned), I see no point in adding dependencies for it. Running mods without `fabricloader` won't work (as far as I know) and also emogg refers to the loader interface, which has not changed over a large number of versions, so I also don't see the point in this dependency. More accurate information about supported versions of Minecraft is automatically implemented using `util.gradle` using the `processResources` process.

Thanks to your screenshot, I made sure that I correctly visualized the problem you mentioned.

**Pull request merged**
