### PR TITLE
Move built-in emojis to a built-in resource pack

### LINKED ISSUE #1: Canon way to disable the built-in emoji
This mod is really cool! We're kind of impressed at how not-a-stacked-birds-nest this codebase is given the results honestly 😅 

if there's not some way to filter out the emoji provided with the mod, would it be possible to split it out into a sample resource pack?

I was thinking of trying to cram the entirety of discord's default twemoji aliases into this if I can find a dump of them somewhere but having a clean start is probably a good idea first.

### PR DESCRIPTION
**Pull request by Abbie5**
fixes #1 

associated config was removed, as it's no longer needed

### CODE REVIEW

**Comment by Abbie5** [comment]
i hope this is a bit more manageable than my last pr :)

**Comment by aratakileo** [comment]
Does Forge have the same ability to add packs?

**Comment by Abbie5** [comment]
yes, but it's a bit more complicated than fabric. neoforged/NeoForge#61 has more details

**Review by aratakileo — APPROVED** [review]
Thank you so much for your contribution to the development of this project!

**Pull request merged**
